config/routes.rb
Rails.application.routes.draw do

  devise_for :views
  devise_for :users
  resources :tweets do
    resources :comments
  end

  root 'pages#index'
  get '/home' => 'pages#home'
  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
  validates :user_id, presence: true #makes sure there is always a user id
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest to oldest tweets
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments  
  validates :user_id, presence: true #makes sure there is always a user id
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) } #newest to oldest tweets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tweets
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  # only load strong parmeters if devise controller is being loaded (refers to sign in, sign up, edit profile pages)

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    # remove username variable from sign in page and account update page so people can't update their username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.tweet_id = params[:tweet_id]
    if @comment.save
      redirect_to "", notice: "You created a comment ;)"
    else
      redirect_to "", notice: "comment not saved. Might be a bug!"
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  helper_method :resource_name, :resource, :devise_mapping

  def index

  end

  def home
    @tweets = Tweet.all
    @newTweet = Tweet.new

    @comment = Comment.new
  end

  def profile
    # get the username from the url :id
    if (User.find_by_username(params[:id]))
      @username = params[:id]
    else
      redirect_to root_path, :notice=> "User not found"
    end
    @tweets = Tweet.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newTweet = Tweet.new
  end

  def explore
    @tweets = Tweet.all
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

def new
  @tweet = Tweet.new
end

def create
  @tweet = Tweet.new(tweet_params)
  @tweet.user_id = current_user.id
  respond_to do |f|
    if (@tweet.save)
      f.html { redirect_to "", notice: "You created a tweet ;)"}
    else
      f.html { redirect_to "", notice: "Post not saved. Might be a bug!"}
    end
  end
end

private
def tweet_params
  params.require(:tweet).permit(:user_id, :content) #doesn't allow user to make
  #changes to someone elses posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <li><a href="/">Home</a></li>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <form class="navbar-form navbar-right">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Navigation
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">

                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">Help</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <%= link_to("Sign Up", new_user_registration_path) %>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <%= link_to("Sign In", new_user_session_path) %>
                        </li>

                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>
    <img class="navbar-brand" src="/legal_hammer.png">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/home">Home</a></li>
                <!-- <li><a href="/">Home</a></li>
                <li><a href="/">Home</a></li>
                <li><a href="/">Home</a></li> -->
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                <form class="navbar-form navbar-right">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search Q&L">
                    </div>

                </form>

                <!-- Dropdown not working -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %>
                        <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <li>
                            <a href="/user/<%= current_user.username %>">Profile</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">Help</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li> <%= link_to('Settings', edit_user_registration_path) %></li>
                        <li role="separator" class="divider"></li>
                        <li> <%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li> <!--custom code for devise gem to log out -->
                    </ul>
                    <li type="button" class="btn btn-primary navbar-btn">Ask a Lawyer</li>

                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render '/layouts/nav' %> <!--Just the short form of the partial -->

<div class="container">
  <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span>
<%= yield %>
</div>
</body>
</html>

app/views/pages/explore.html.erb
<div class="col-xs-6">
        <% for @t in @tweets %>
        <div class="panel panel-default">
            <div class="panel-body">
                <p><%= @t.content %></p>
            </div>
        </div>
        <% end %>
    </div>

app/views/pages/home.html.erb
<center>
<h1> Q&L </h1>

<h5>Where A Lawyer Will Answer Your Legal Question In 4 lines or Less!</h5>
</center> <br>


<div class="row">
    <div class="col-xs-3">
        <h5>Find A Lawyer</h5><br>
        <div class="panel panel-default find-a-lawyer">
            <div class="panel-body">
                <p class="find-a-lawyer"></p>
            </div>
        </div>
        <div class="panel panel-default">

        </div>
    </div>

    <div class="col-xs-6">
      <%= render 'components/post_form' %> <br><br>
      <% for @t in @tweets %>
          <div class="panel panel-default post-panel">
              <div class="panel-body row">
                  <div class="col-sm-1">
                      <img src="confused_person.jpeg" height="50px" width="50px">
                  </div>
                  <div class="col-sm-11">
                      <p><span class="post-owner"><%= User.find(@t.user_id).username %></span> - <span class="post-creation"> <%= @t.created_at.to_formatted_s(:short) %></p></span>
                      <div class="panel panel-default the-content">
                          <div class="panel-body">
                      <p><span class="post-content"><%= @t.content %></p></span>
                  </div>

                      </div>
                  </div>
              </div>



</div>
        <div class="the-comment">
              <% @t.comments.each do |comment| %>
            <div class="panel panel-default the-comment">
                <div class="panel-body">

                    <div class="col-sm-1">
                        <img src="judge.jpg" height="50px" width="50px">
                    </div>
                    <div class="col-sm-11">
                        <p><span class="comment-owner"><%= User.find(comment.user_id).username %></span> - <span class="comment-creation"> <%= comment.created_at.to_formatted_s(:short) %></p></span>

                    <p class="comment-content"> <%= comment.content %> </p>
                </div>
            </div>
            </div>


              <% end %>
        </div>





      <%= render 'components/post_form_comments', :locals => {tweet: @t} %>
      <% end %>


    <div class="col-xs-3">
        <div class="panel panel-default">

        </div>
    </div>
</div>

app/views/pages/index.html.erb
<% if !user_signed_in? %>
<style>
body {
  background: linear-gradient(
rgba(0, 0, 0, 0.7),
rgba(0, 0, 0, 0.7)
), url("/bg.jpg") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

h1 {
  color: white;
  font-weight: bold;
}

h3 {
  color: white;
  font-weight: bold;
}

.container-index {
  margin-left: 15%;
  margin-right: 15%;
  color: white;
  display: block;
}

.text {
  color: white;
  font-weight: heavy;
  font-size: 150%;
}

.log-in {
  float: right;
  width: 200px;
  height: 175px;
  margin-top: 7.5%;
  display: block;
}

.sign-up {
  float: right;
  width: 200px;
  height: 300px;
  display: block;
  color: black;
  margin-left: -100px;
}

.sign-in-up {
  margin-left: 190px;
}


</style>
<div class="container-index row">
  <div class="col-sm-6">
  <h1>Welcome To Q&L </h1>
  <h3>Question and Lawyer </h3>

<p class="text">
  Get an answer to your legal problem in 4 lines or less!
</p>
  </div>

<div class="col-sm-6">

  <h5 class="sign-in-up">Sign In</h5>
  <div class="log-in panel">

    <%= form_for(:user, :url => session_path(:user)) do |f| %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
    <%= f.submit 'Sign in', :class => 'sign-in-button' %>
    <%= link_to "Forgot your password?", new_password_path(:user) %>
    <% end %>

  </div>
</div>

<div class="col-sm-6"></div>

<div class="col-sm-6">
  <h5 class="sign-in-up">Sign Up</h5><br>
  <div class="sign-up sign-up-container panel">
    <%= render :partial => 'devise/registrations/new_registration' %>
  </div>
</div>

</div>

<% else %>

<script> document.location = "/home" </script>

<% end %>

app/views/pages/profile.html.erb
<!-- <div class="row">
    <div class="col-xs-12">
        <div class="jumbotron">
            <% @username %>
        </div>
    </div>

</div> -->

<!-- begin row 2 -->
<div class="col-xs-3"></div>


    <div class="col-xs-6">
        <%= render 'components/post_form' %> <br><br>
            <% for @t in @tweets %>
            <div class="panel panel-default post-panel">
                <div class="panel-body row">
                    <div class="col-sm-1">
                        <img src="legal_hammer.png" height="50px" width="50px">
                    </div>

                    <div class="col-sm-11">
                        <p><span class="post-owner"><%= User.find(@t.user_id).username %></span> - <span class="post-creation"> <%= @t.created_at.to_formatted_s(:short) %></p></span>
                        <p><span class="post-content"><%= @t.content %></p></span>
                    </div>


                </div>
            </div>
            <% end %>

    <div class="col-xs-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>Lawyers You May Know</p>
            </div>
        </div>
    </div>
</div>